# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/corelanc0d3r/mnt/CDev/pyencfsgui/encfsgui_newmasterkey.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(358, 160)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(358, 160))
        Dialog.setBaseSize(QtCore.QSize(358, 160))
        Dialog.setModal(True)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 311, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 311, 16))
        self.label_2.setObjectName("label_2")
        self.txt_password1 = QtWidgets.QLineEdit(Dialog)
        self.txt_password1.setGeometry(QtCore.QRect(20, 30, 311, 21))
        self.txt_password1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password1.setObjectName("txt_password1")
        self.txt_password2 = QtWidgets.QLineEdit(Dialog)
        self.txt_password2.setGeometry(QtCore.QRect(20, 80, 311, 21))
        self.txt_password2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password2.setObjectName("txt_password2")
        self.btn_OK = QtWidgets.QPushButton(Dialog)
        self.btn_OK.setGeometry(QtCore.QRect(20, 120, 113, 32))
        self.btn_OK.setObjectName("btn_OK")
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(220, 120, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Please enter the master password:"))
        self.label_2.setText(_translate("Dialog", "Verify master password:"))
        self.btn_OK.setText(_translate("Dialog", "OK"))
        self.btn_cancel.setText(_translate("Dialog", "Cancel"))
