# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/corelanc0d3r/mnt/CDev/pyencfsgui/encfsgui_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmEnterPassword(object):
    def setupUi(self, frmEnterPassword):
        frmEnterPassword.setObjectName("frmEnterPassword")
        frmEnterPassword.setWindowModality(QtCore.Qt.ApplicationModal)
        frmEnterPassword.resize(470, 160)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmEnterPassword.sizePolicy().hasHeightForWidth())
        frmEnterPassword.setSizePolicy(sizePolicy)
        frmEnterPassword.setMinimumSize(QtCore.QSize(470, 160))
        frmEnterPassword.setBaseSize(QtCore.QSize(470, 160))
        frmEnterPassword.setFocusPolicy(QtCore.Qt.StrongFocus)
        frmEnterPassword.setModal(True)
        self.lbl_line1 = QtWidgets.QLabel(frmEnterPassword)
        self.lbl_line1.setGeometry(QtCore.QRect(50, 10, 221, 16))
        self.lbl_line1.setObjectName("lbl_line1")
        self.lbl_enc_path = QtWidgets.QLabel(frmEnterPassword)
        self.lbl_enc_path.setGeometry(QtCore.QRect(50, 30, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_enc_path.setFont(font)
        self.lbl_enc_path.setObjectName("lbl_enc_path")
        self.lbl_line2 = QtWidgets.QLabel(frmEnterPassword)
        self.lbl_line2.setGeometry(QtCore.QRect(50, 50, 221, 16))
        self.lbl_line2.setObjectName("lbl_line2")
        self.lbl_mount_path = QtWidgets.QLabel(frmEnterPassword)
        self.lbl_mount_path.setGeometry(QtCore.QRect(50, 70, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mount_path.setFont(font)
        self.lbl_mount_path.setObjectName("lbl_mount_path")
        self.txt_password = QtWidgets.QLineEdit(frmEnterPassword)
        self.txt_password.setGeometry(QtCore.QRect(60, 100, 331, 21))
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setObjectName("txt_password")
        self.btn_OK = QtWidgets.QPushButton(frmEnterPassword)
        self.btn_OK.setGeometry(QtCore.QRect(10, 130, 113, 32))
        self.btn_OK.setObjectName("btn_OK")
        self.btn_cancel = QtWidgets.QPushButton(frmEnterPassword)
        self.btn_cancel.setGeometry(QtCore.QRect(340, 130, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")
        self.lbl_image = QtWidgets.QLabel(frmEnterPassword)
        self.lbl_image.setGeometry(QtCore.QRect(10, 10, 32, 32))
        self.lbl_image.setText("")
        self.lbl_image.setPixmap(QtGui.QPixmap("/Users/corelanc0d3r/mnt/CDev/pyencfsgui/bitmaps/icons8-lock-32.png"))
        self.lbl_image.setObjectName("lbl_image")

        self.retranslateUi(frmEnterPassword)
        QtCore.QMetaObject.connectSlotsByName(frmEnterPassword)

    def retranslateUi(self, frmEnterPassword):
        _translate = QtCore.QCoreApplication.translate
        frmEnterPassword.setWindowTitle(_translate("frmEnterPassword", "Please enter password"))
        self.lbl_line1.setText(_translate("frmEnterPassword", "Please enter password to mount"))
        self.lbl_enc_path.setText(_translate("frmEnterPassword", "lbl_enc_path"))
        self.lbl_line2.setText(_translate("frmEnterPassword", "as"))
        self.lbl_mount_path.setText(_translate("frmEnterPassword", "lbl_mount_path"))
        self.btn_OK.setText(_translate("frmEnterPassword", "OK"))
        self.btn_cancel.setText(_translate("frmEnterPassword", "Cancel"))
